steps:
  - command: "scripts/ci/build.sh"
    label: ":hammer: Build"
    agents:
      agent: "ci"

  - wait

  - command: "scripts/ci/test.sh"
    label: ":llama: Test"
    agents:
      agent: "ci"

  - wait

  - command: "scripts/ci/publish.sh"
    label: ":ship: Publish"
    agents:
      agent: "ci"
